INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("","",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("AED","United Arab Emirates Dirham",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("AFN","Afghanistan Afghani",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("ALL","Albania Lek",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("AMD","Armenia Dram",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("ANG","Netherlands Antilles Guilder",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("AOA","Angola Kwanza",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("ARS","Argentina Peso",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("AUD","Australia Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("AWG","Aruba Guilder",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("AZN","Azerbaijan New Manat",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("BAM","Bosnia and Herzegovina Convertible Marka",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("BBD","Barbados Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("BDT","Bangladesh Taka",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("BGN","Bulgaria Lev",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("BHD","Bahrain Dinar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("BIF","Burundi Franc",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("BMD","Bermuda Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("BND","Brunei Darussalam Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("BOB","Bolivia Bolíviano",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("BRL","Brazil Real",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("BSD","Bahamas Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("BTN","Bhutan Ngultrum",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("BWP","Botswana Pula",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("BYR","Belarus Ruble",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("BZD","Belize Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("CAD","Canada Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("CDF","Congo/Kinshasa Franc",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("CHF","Switzerland Franc",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("CLP","Chile Peso",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("CNY","China Yuan Renminbi",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("COP","Colombia Peso",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("CRC","Costa Rica Colon",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("CUC","Cuba Convertible Peso",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("CUP","Cuba Peso",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("CVE","Cape Verde Escudo",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("CZK","Czech Republic Koruna",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("DJF","Djibouti Franc",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("DKK","Denmark Krone",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("DOP","Dominican Republic Peso",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("DZD","Algeria Dinar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("EGP","Egypt Pound",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("ERN","Eritrea Nakfa",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("ETB","Ethiopia Birr",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("EUR","Euro Member Countries",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("FJD","Fiji Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("FKP","Falkland Islands (Malvinas) Pound",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("GBP","United Kingdom Pound",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("GEL","Georgia Lari",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("GGP","Guernsey Pound",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("GHS","Ghana Cedi",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("GIP","Gibraltar Pound",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("GMD","Gambia Dalasi",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("GNF","Guinea Franc",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("GTQ","Guatemala Quetzal",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("GYD","Guyana Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("HKD","Hong Kong Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("HNL","Honduras Lempira",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("HRK","Croatia Kuna",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("HTG","Haiti Gourde",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("HUF","Hungary Forint",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("IDR","Indonesia Rupiah",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("ILS","Israel Shekel",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("IMP","Isle of Man Pound",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("INR","India Rupee",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("IQD","Iraq Dinar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("IRR","Iran Rial",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("ISK","Iceland Krona",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("JEP","Jersey Pound",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("JMD","Jamaica Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("JOD","Jordan Dinar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("JPY","Japan Yen",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("KES","Kenya Shilling",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("KGS","Kyrgyzstan Som",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("KHR","Cambodia Riel",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("KMF","Comoros Franc",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("KPW","Korea (North) Won",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("KRW","Korea (South) Won",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("KWD","Kuwait Dinar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("KYD","Cayman Islands Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("KZT","Kazakhstan Tenge",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("LAK","Laos Kip",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("LBP","Lebanon Pound",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("LKR","Sri Lanka Rupee",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("LRD","Liberia Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("LSL","Lesotho Loti",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("LYD","Libya Dinar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("MAD","Morocco Dirham",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("MDL","Moldova Leu",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("MGA","Madagascar Ariary",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("MKD","Macedonia Denar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("MMK","Myanmar (Burma) Kyat",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("MNT","Mongolia Tughrik",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("MOP","Macau Pataca",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("MRO","Mauritania Ouguiya",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("MUR","Mauritius Rupee",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("MVR","Maldives (Maldive Islands) Rufiyaa",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("MWK","Malawi Kwacha",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("MXN","Mexico Peso",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("MYR","Malaysia Ringgit",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("MZN","Mozambique Metical",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("NAD","Namibia Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("NGN","Nigeria Naira",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("NIO","Nicaragua Cordoba",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("NOK","Norway Krone",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("NPR","Nepal Rupee",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("NZD","New Zealand Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("OMR","Oman Rial",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("PAB","Panama Balboa",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("PEN","Peru Sol",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("PGK","Papua New Guinea Kina",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("PHP","Philippines Peso",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("PKR","Pakistan Rupee",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("PLN","Poland Zloty",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("PYG","Paraguay Guarani",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("QAR","Qatar Riyal",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("RON","Romania New Leu",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("RSD","Serbia Dinar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("RUB","Russia Ruble",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("RWF","Rwanda Franc",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("SAR","Saudi Arabia Riyal",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("SBD","Solomon Islands Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("SCR","Seychelles Rupee",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("SDG","Sudan Pound",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("SEK","Sweden Krona",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("SGD","Singapore Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("SHP","Saint Helena Pound",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("SLL","Sierra Leone Leone",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("SOS","Somalia Shilling",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("SPL","Seborga Luigino",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("SRD","Suriname Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("STD","São Tomé and Príncipe Dobra",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("SVC","El Salvador Colon",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("SYP","Syria Pound",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("SZL","Swaziland Lilangeni",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("THB","Thailand Baht",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("TJS","Tajikistan Somoni",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("TMT","Turkmenistan Manat",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("TND","Tunisia Dinar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("TOP","Tonga Pa'anga",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("TRY","Turkey Lira",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("TTD","Trinidad and Tobago Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("TVD","Tuvalu Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("TWD","Taiwan New Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("TZS","Tanzania Shilling",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("UAH","Ukraine Hryvnia",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("UGX","Uganda Shilling",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("USD","United States Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("UYU","Uruguay Peso",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("UZS","Uzbekistan Som",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("VEF","Venezuela Bolivar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("VND","Viet Nam Dong",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("VUV","Vanuatu Vatu",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("WST","Samoa Tala",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("XAF","Communauté Financière Africaine (BEAC) CFA Franc BEAC",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("XCD","East Caribbean Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("XDR","International Monetary Fund (IMF) Special Drawing Rights",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("XOF","Communauté Financière Africaine (BCEAO) Franc",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("XPF","Comptoirs Français du Pacifique (CFP) Franc",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("YER","Yemen Rial",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("ZAR","South Africa Rand",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("ZMW","Zambia Kwacha",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("ZWD","Zimbabwe Dollar",now(),now());
INSERT INTO deal_currency (code_name,name,created_date,last_updated_date) VALUES ("","",now(),now());